"""harden CRM domain

Revision ID: 25ec27f4465c
Revises: 70a70ab79a80
Create Date: 2026-09-03 12:48:18.496046
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '25ec27f4465c'
down_revision: Union[str, None] = '70a70ab79a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name='fk_audit_events_actor_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_audit_events_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_tenant_created_at', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_tenant_entity', 'audit_events', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.add_column('campaigns', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signals', sa.Column('evidence_id', sa.Uuid(), nullable=True))
    op.add_column('signals', sa.Column('fingerprint', sa.String(length=128), nullable=True))
    op.add_column('signals', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_signals_evidence_id'), 'signals', ['evidence_id'], unique=False)
    op.create_index('uq_signals_tenant_fingerprint', 'signals', ['tenant_id', 'fingerprint'], unique=True)
    op.create_foreign_key('fk_signals_evidence_id', 'signals', 'evidence', ['evidence_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_constraint('fk_signals_evidence_id', 'signals', type_='foreignkey')
    op.drop_index('uq_signals_tenant_fingerprint', table_name='signals')
    op.drop_index(op.f('ix_signals_evidence_id'), table_name='signals')
    op.drop_column('signals', 'deleted_at')
    op.drop_column('signals', 'fingerprint')
    op.drop_column('signals', 'evidence_id')
    op.drop_column('opportunities', 'deleted_at')
    op.drop_column('notes', 'deleted_at')
    op.drop_column('campaigns', 'deleted_at')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_tenant_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_tenant_created_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
