"""add evidence qualification and lead scoring

Revision ID: b8d2ab04083b
Revises: 25ec27f4465c
Create Date: 2026-09-03 13:15:59.318038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'b8d2ab04083b'
down_revision: Union[str, None] = '25ec27f4465c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('lead_id', sa.Uuid(), nullable=True))
    op.add_column('evidence', sa.Column('source_name', sa.String(length=255), nullable=True))
    op.add_column('evidence', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('evidence', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evidence', sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('evidence', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evidence', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_evidence_tenant_collected', 'evidence', ['tenant_id', 'collected_at'], unique=False)
    op.create_index('ix_evidence_tenant_hash', 'evidence', ['tenant_id', 'content_hash'], unique=False)
    op.create_index('ix_evidence_tenant_lead', 'evidence', ['tenant_id', 'lead_id'], unique=False)
    op.create_index('ix_evidence_tenant_type', 'evidence', ['tenant_id', 'evidence_type'], unique=False)
    op.create_foreign_key('fk_evidence_lead_id', 'evidence', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('qualification_status', sa.String(length=50), server_default='unqualified', nullable=False))
    op.add_column('leads', sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('qualified_by', sa.Uuid(), nullable=True))
    op.add_column('leads', sa.Column('fit_score', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('intent_score', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('signal_score', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('data_confidence', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('freshness_score', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('scoring_version', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('score_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_leads_qualification_status'), 'leads', ['qualification_status'], unique=False)
    op.create_index('ix_leads_tenant_qualification', 'leads', ['tenant_id', 'qualification_status'], unique=False)
    op.create_index('ix_leads_tenant_score', 'leads', ['tenant_id', 'score'], unique=False)
    op.create_foreign_key('fk_leads_qualified_by', 'leads', 'users', ['qualified_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_leads_qualified_by', 'leads', type_='foreignkey')
    op.drop_index('ix_leads_tenant_score', table_name='leads')
    op.drop_index('ix_leads_tenant_qualification', table_name='leads')
    op.drop_index(op.f('ix_leads_qualification_status'), table_name='leads')
    op.drop_column('leads', 'score_explanation')
    op.drop_column('leads', 'scoring_version')
    op.drop_column('leads', 'freshness_score')
    op.drop_column('leads', 'data_confidence')
    op.drop_column('leads', 'signal_score')
    op.drop_column('leads', 'intent_score')
    op.drop_column('leads', 'fit_score')
    op.drop_column('leads', 'qualified_by')
    op.drop_column('leads', 'qualified_at')
    op.drop_column('leads', 'qualification_status')
    op.drop_constraint('fk_evidence_lead_id', 'evidence', type_='foreignkey')
    op.drop_index('ix_evidence_tenant_type', table_name='evidence')
    op.drop_index('ix_evidence_tenant_lead', table_name='evidence')
    op.drop_index('ix_evidence_tenant_hash', table_name='evidence')
    op.drop_index('ix_evidence_tenant_collected', table_name='evidence')
    op.drop_column('evidence', 'created_at')
    op.drop_column('evidence', 'metadata')
    op.drop_column('evidence', 'confidence')
    op.drop_column('evidence', 'published_at')
    op.drop_column('evidence', 'excerpt')
    op.drop_column('evidence', 'source_name')
    op.drop_column('evidence', 'lead_id')
    # ### end Alembic commands ###
