"""add multi-tenancy and IAM

Revision ID: b8ee741a3612
Revises: bb51fc2cce1a
Create Date: 2026-09-03 11:30:53.105760
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'b8ee741a3612'
down_revision: Union[str, None] = 'bb51fc2cce1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_tenant_id'), 'workspaces', ['tenant_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Maps users to workspaces with a role per workspace'
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.add_column('companies', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'companies', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('contacts', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_contacts_company_id', table_name='contacts')
    op.create_index('ix_contacts_tenant_company', 'contacts', ['tenant_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'contacts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('evidence', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_evidence_company_id', table_name='evidence')
    op.drop_index('ix_evidence_contact_id', table_name='evidence')
    op.create_index('ix_evidence_tenant_company', 'evidence', ['tenant_id', 'company_id'], unique=False)
    op.create_index('ix_evidence_tenant_contact', 'evidence', ['tenant_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'evidence', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('leads', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_leads_company_id', table_name='leads')
    op.drop_index('ix_leads_contact_id', table_name='leads')
    op.create_index('ix_leads_tenant_company', 'leads', ['tenant_id', 'company_id'], unique=False)
    op.create_index('ix_leads_tenant_contact', 'leads', ['tenant_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index('ix_leads_tenant_contact', table_name='leads')
    op.drop_index('ix_leads_tenant_company', table_name='leads')
    op.create_index('ix_leads_contact_id', 'leads', ['contact_id'], unique=False)
    op.create_index('ix_leads_company_id', 'leads', ['company_id'], unique=False)
    op.drop_column('leads', 'tenant_id')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index('ix_evidence_tenant_contact', table_name='evidence')
    op.drop_index('ix_evidence_tenant_company', table_name='evidence')
    op.create_index('ix_evidence_contact_id', 'evidence', ['contact_id'], unique=False)
    op.create_index('ix_evidence_company_id', 'evidence', ['company_id'], unique=False)
    op.drop_column('evidence', 'tenant_id')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index('ix_contacts_tenant_company', table_name='contacts')
    op.create_index('ix_contacts_company_id', 'contacts', ['company_id'], unique=False)
    op.drop_column('contacts', 'tenant_id')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_column('companies', 'tenant_id')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_tenant_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
