"""add outreach policy engine

Revision ID: f861027429a7
Revises: b8d2ab04083b
Create Date: 2026-09-03 14:12:47.677213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'f861027429a7'
down_revision: Union[str, None] = 'b8d2ab04083b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_tenant_id'), 'message_templates', ['tenant_id'], unique=False)
    op.create_index('ix_templates_tenant_channel', 'message_templates', ['tenant_id', 'channel'], unique=False)
    op.create_index('ix_templates_tenant_name', 'message_templates', ['tenant_id', 'name'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('basis', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_consents_contact_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_consents_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consents_tenant_contact', 'consents', ['tenant_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_consents_tenant_id'), 'consents', ['tenant_id'], unique=False)
    op.create_table('do_not_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_dnc_company_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_dnc_contact_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_dnc_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dnc_tenant_channel', 'do_not_contacts', ['tenant_id', 'channel'], unique=False)
    op.create_index('ix_dnc_tenant_company', 'do_not_contacts', ['tenant_id', 'company_id'], unique=False)
    op.create_index('ix_dnc_tenant_contact', 'do_not_contacts', ['tenant_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_do_not_contacts_tenant_id'), 'do_not_contacts', ['tenant_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='fk_policy_decisions_campaign_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_policy_decisions_contact_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_policy_decisions_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='fk_policy_decisions_lead_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_decision'), 'policy_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_policy_decisions_tenant_id'), 'policy_decisions', ['tenant_id'], unique=False)
    op.create_index('ix_policy_tenant_created', 'policy_decisions', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_policy_tenant_lead', 'policy_decisions', ['tenant_id', 'lead_id'], unique=False)
    op.create_table('outreach_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('policy_decision_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='fk_outreach_campaign_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_outreach_contact_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='fk_outreach_lead_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], name='fk_outreach_policy_decision_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], name='fk_outreach_template_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_requests_status'), 'outreach_requests', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_requests_tenant_id'), 'outreach_requests', ['tenant_id'], unique=False)
    op.create_index('ix_outreach_tenant_lead', 'outreach_requests', ['tenant_id', 'lead_id'], unique=False)
    op.create_index('ix_outreach_tenant_status', 'outreach_requests', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_outreach_tenant_idempotency', 'outreach_requests', ['tenant_id', 'idempotency_key'], unique=True)
    op.add_column('campaigns', sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'policy')
    op.drop_index('uq_outreach_tenant_idempotency', table_name='outreach_requests')
    op.drop_index('ix_outreach_tenant_status', table_name='outreach_requests')
    op.drop_index('ix_outreach_tenant_lead', table_name='outreach_requests')
    op.drop_index(op.f('ix_outreach_requests_tenant_id'), table_name='outreach_requests')
    op.drop_index(op.f('ix_outreach_requests_status'), table_name='outreach_requests')
    op.drop_table('outreach_requests')
    op.drop_index('ix_policy_tenant_lead', table_name='policy_decisions')
    op.drop_index('ix_policy_tenant_created', table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_tenant_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_decision'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_do_not_contacts_tenant_id'), table_name='do_not_contacts')
    op.drop_index('ix_dnc_tenant_contact', table_name='do_not_contacts')
    op.drop_index('ix_dnc_tenant_company', table_name='do_not_contacts')
    op.drop_index('ix_dnc_tenant_channel', table_name='do_not_contacts')
    op.drop_table('do_not_contacts')
    op.drop_index(op.f('ix_consents_tenant_id'), table_name='consents')
    op.drop_index('ix_consents_tenant_contact', table_name='consents')
    op.drop_table('consents')
    op.drop_index('ix_templates_tenant_name', table_name='message_templates')
    op.drop_index('ix_templates_tenant_channel', table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_tenant_id'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
